### PR TITLE
Allow multiple arguments in ic()

### PR DESCRIPTION
**Pull request by DominikRafacz**
Some implementations of icecream for other languages allow ic() to take arbitrary number of arguments. Changing underlying infrastructure costs almost nothing. So I've just done it.

### CODE REVIEW

**Comment by DominikRafacz** [comment]
Okay, there are lots of commits, but I simply haven't noticed that branch "develop" does not contain changes recently committed to main. Well, "recently"... for a long time there's been nothing fun happening here!

**Comment by lewinfox** [comment]
Fixes #13 by adding `R CMD check`

**Comment by lewinfox** [comment]
@DominikRafacz should Laura be added to the contributor list in `DESCRIPTION` and so on?

**Comment by DominikRafacz** [comment]
> @DominikRafacz should Laura be added to the contributor list in `DESCRIPTION` and so on?

I think it would be reasonable; I guess she will make some more contributions soon.

**Comment by DominikRafacz** [comment]
I've added @ErdaradunGaztea as contributor to DESCRIPTION. @lewinfox I think it is ready to merge if you do not have any objections

**Review by lewinfox — APPROVED** [review]

**Pull request merged**
